from __future__ import annotations

from collections.abc import Callable, Generator
from typing import Any, Protocol

from syncraft.errors import HTTPException, status

from syncraft.database import DatabaseManager, get_db
from syncraft.services.mongo_storage import MongoStorageService
from syncraft.services.storage import StorageService


class StorageBackend(Protocol):
    def get_settings(self): ...
    def update_settings(self, payload): ...
    def list_activity_logs(self, limit: int = 200): ...
    def clear_activity_logs(self) -> None: ...
    def list_channels(self): ...
    def create_channel(self, payload): ...
    def get_channel(self, channel_id: str): ...
    def update_channel(self, channel_id: str, payload, log_activity: bool = True): ...
    def delete_channel(self, channel_id: str) -> None: ...
    def list_templates(self): ...
    def create_template(self, payload): ...
    def update_template(self, template_id: str, payload): ...
    def delete_template(self, template_id: str) -> None: ...
    def list_variables(self): ...
    def create_variable(self, payload): ...
    def update_variable(self, variable_id: str, payload): ...
    def delete_variable(self, variable_id: str) -> None: ...
    def list_assets(self): ...
    def create_asset(self, payload): ...
    def update_asset(self, asset_id: str, payload): ...
    def get_asset(self, asset_id: str): ...
    def mirror_asset(self, asset_id: str, channel_ids: list[str]): ...
    def delete_asset(self, asset_id: str) -> None: ...
    def sync_remote_assets(self): ...
    def list_messages(self): ...
    def sync_remote_messages(self): ...
    def create_remote_assets(self, payloads): ...
    def list_api_keys(self): ...
    def create_api_key(self, payload): ...
    def update_api_key(self, api_key_id: str, payload): ...
    def delete_api_key(self, api_key_id: str) -> None: ...
    def list_webhooks(self): ...
    def create_webhook(self, payload): ...
    def update_webhook(self, webhook_id: str, payload): ...
    def delete_webhook(self, webhook_id: str) -> None: ...
    def log_activity(self, **kwargs): ...


StorageDependency = Callable[[], Generator[StorageBackend, None, None]]


def build_storage_dependency(
    database_manager: DatabaseManager,
) -> StorageDependency:
    def storage_dependency() -> Generator[StorageBackend, None, None]:
        current_engine = database_manager.config.database_engine
        if current_engine in {"sqlite", "postgresql", "mysql"}:
            yield from _sql_storage_dependency(database_manager)
            return
        if current_engine == "mongodb":
            yield MongoStorageService(database_manager.mongo_database)
            return
        raise HTTPException(
            status_code=status.HTTP_501_NOT_IMPLEMENTED,
            detail=f"Storage engine '{current_engine}' is not implemented yet",
        )
        yield

    return storage_dependency


def _sql_storage_dependency(
    database_manager: DatabaseManager,
) -> Generator[StorageBackend, None, None]:
    for session in get_db(database_manager.session_factory):
        yield StorageService(session)
